[package]
name = "edit_data"
version = "0.1.0"
authors = ["martin <m.e@acm.org>"]
edition = "2018"

[dependencies]
anglican_calendar = { path = ".." }
ansi_term = "0.12.1"
structopt = "0.3.21"
ron = "0.6.2"
serde_derive = "1.0.117"

